### ISSUE TITLE
Logo size on mobile 

### ISSUE THREAD

**Issue by leobardogudino** [Afrothundr/broccoli-legacy#28]
The logo size on mobile appears too big and sits outside of the top nav container
![Uploading Screenshot 2024-09-09 at 1.26.08 PM.jpeg…]()

**Comment by Afrothundr** [comment]
Could you reupload this screen shot? I'm unable to reproduce!

**Comment by leobardogudino** [comment]
![Screenshot 2024-09-17 at 12 49 20 PM](https://github.com/user-attachments/assets/0d03432f-b6a0-431e-9d90-8b6acc5da658)

**Comment by leobardogudino** [comment]
Hopefully this works
